version: 0.2
phases:
  install:
    commands:
      - npm ci
  pre_build:
    commands:
      - npm run test
      - npm prune --production
  build:
    commands:
      - npm run build
      - aws cloudformation package --template template.yaml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
